name: Deploy Main

on:
  push:
    branches:
      - main

jobs:
  staging:
    environment: staging
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "Went to staging!"

  production:
    environment: production
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "Went to staging!"
